export const customer_data = [
  {
    id: "1",
    name: "Esther Dunkwu",
    location: "Lagos",
    email: "Esther@gmail.com",
    lastAct: "2 hrs ago",
    status: "active",
  },
  {
    id: "2",
    name: "Esther Dunkwu",
    location: "Lagos",
    email: "Esther@gmail.com",
    lastAct: "21/09/2022",
    status: "disabled",
  },
  {
    id: "3",
    name: "Esther Dunkwu",
    location: "Lagos",
    email: "Esther@gmail.com",
    lastAct: "21/09/2022",
    status: "disabled",
  },
  {
    id: "4",
    name: "Esther Dunkwu",
    location: "Lagos",
    email: "Esther@gmail.com",
    lastAct: "21/09/2022",
    status: "active",
  },
  {
    id: "5",
    name: "Esther Dunkwu",
    location: "Lagos",
    email: "Esther@gmail.com",
    lastAct: "21/09/2022",
    status: "active",
  },
  {
    id: "6",
    name: "Esther Dunkwu",
    location: "Lagos",
    email: "Esther@gmail.com",
    lastAct: "21/09/2022",
    status: "active",
  },
  {
    id: "7",
    name: "Esther Dunkwu",
    location: "Lagos",
    email: "Esther@gmail.com",
    lastAct: "21/09/2022",
    status: "active",
  },
  {
    id: "8",
    name: "Esther Dunkwu",
    location: "Lagos",
    email: "Esther@gmail.com",
    lastAct: "21/09/2022",
    status: "active",
  },
];

// export const customer_columns = [
//   { Header: "Name", accessor: "name" },
//   { Header: "Location", accessor: "location" },
//   { Header: "Email", accessor: "email" },
//   { Header: "Last Activity", accessor: "lastAct" },
// ];

export const vendor_data = [
  {
    id: "1",
    name: "ABC Ventures",
    location: "Lagos",
    email: "Esther@gmail.com",
    status: "pending",
    type: "old",
  },
  {
    id: "2",
    name: "ABC Ventures",
    location: "Lagos",
    email: "Esther@gmail.com",
    status: "pending",
    type: "new",
  },
  {
    id: "3",
    name: "ABC Ventures",
    location: "Lagos",
    email: "Esther@gmail.com",
    status: "pending",
    type: "old",
  },
  {
    id: "4",
    name: "ABC Ventures",
    location: "Lagos",
    email: "Esther@gmail.com",
    status: "onboarded",
    type: "old",
  },
  {
    id: "5",
    name: "ABC Ventures",
    location: "Lagos",
    email: "Esther@gmail.com",
    status: "onboarded",
    type: "old",
  },
  {
    id: "6",
    name: "ABC Ventures",
    location: "Lagos",
    email: "Esther@gmail.com",
    status: "rejected",
    type: "old",
  },
  {
    id: "7",
    name: "ABC Ventures",
    location: "Lagos",
    email: "Esther@gmail.com",
    status: "onboarded",
    type: "old",
  },
];

// export const vendor_columns = [
//   { Header: "Name", accessor: "name" },
//   { Header: "Location", accessor: "location" },
//   { Header: "Email", accessor: "email" },
//   { Header: "Last Activity", accessor: "lastAct" },
// ];

export const admin_data = [
  {
    id: "1",
    name: "Bernard Charles",
    category: "Super Admin",
    email: "Esther@gmail.com",
    action: "deactivate",
  },
  {
    id: "2",
    name: "Bernard Charles",
    category: "Admin",
    email: "Esther@gmail.com",
    action: "deactivate",
  },
  {
    id: "3",
    name: "Bernard Charles",
    category: "Admin",
    email: "Esther@gmail.com",
    action: "deactivate",
  },
  {
    id: "4",
    name: "Bernard Charles",
    category: "Admin",
    email: "Esther@gmail.com",
    action: "deactivated",
  },
  {
    id: "5",
    name: "Bernard Charles",
    category: "Admin",
    email: "Esther@gmail.com",
    action: "deactivate",
  },
  {
    id: "6",
    name: "Bernard Charles",
    category: "Admin",
    email: "Esther@gmail.com",
    action: "deactivate",
  },
];
